/** Shared button / menu labels (Telegram reply keyboard + Discord panels). */
export const BTN = {
  addWorker: "➕ Thêm người vào tổ",
  listWorkers: "👥 Hiện danh sách tổ",
  editWorker: "✏️ Sửa người trong tổ",
  addEvent: "📝 Thêm phát sinh",
  deleteEvent: "🗑️ Xóa phát sinh",
  statsMonth: "📊 Thống kê tháng",
  addMachine: "🏭 Thêm máy",
  listMachines: "📋 Danh sách máy",
  editMachine: "✏️ Sửa máy",
  deleteMachine: "🗑️ Xóa máy",
  deactivate: "🚫 Ngưng công nhân",
  cancel: "❌ Hủy",
  today: "Hôm nay",
  thisMonth: "Tháng này",
  skipNote: "Bỏ qua ghi chú",
} as const;

export function startGuideText(platformLabel: string): string {
  return [
    "Chào bạn.",
    `Mỗi tài khoản ${platformLabel} quản lý tổ riêng (dữ liệu không dùng chung).`,
    "",
    "Gợi ý bắt đầu:",
    `1. ${BTN.addMachine}`,
    `2. ${BTN.addWorker} (chọn ca + máy)`,
    `3. ${BTN.addEvent} khi có phát sinh`,
    `4. ${BTN.statsMonth} để xem bảng công`,
    "",
    "Menu:",
    "",
    "Công nhân",
    `• ${BTN.addWorker} — thêm người vào tổ`,
    `• ${BTN.listWorkers} — xem danh sách theo ca`,
    `• ${BTN.editWorker} — sửa tên / năm sinh / ca / máy`,
    `• ${BTN.deactivate} — ngưng công nhân`,
    "",
    "Phát sinh & thống kê",
    `• ${BTN.addEvent} — ghi nghỉ / tăng ca / về sớm / đến muộn`,
    `• ${BTN.deleteEvent} — xóa phát sinh`,
    `• ${BTN.statsMonth} — xem bảng công tháng`,
    "",
    "Máy",
    `• ${BTN.addMachine} — thêm máy`,
    `• ${BTN.listMachines} — xem danh sách máy`,
    `• ${BTN.editMachine} — đổi tên máy`,
    `• ${BTN.deleteMachine} — xóa máy (khi không còn người gán)`,
    "",
    `Trong thao tác, bấm «${BTN.cancel}» để hủy.`,
  ].join("\n");
}
